# Generated by Django 2.2.6 on 2019-11-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalWeights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_completed', models.IntegerField(default=0)),
                ('goals_missed', models.IntegerField(default=0)),
                ('existing_goals', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'weights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObservationWeights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep', models.FloatField(default=1)),
                ('daily_exercise', models.FloatField(default=1)),
                ('weekly_exercise', models.FloatField(default=1)),
                ('daily_work', models.FloatField(default=1)),
                ('weekly_work', models.FloatField(default=1)),
                ('daily_meals', models.IntegerField(default=1)),
                ('past_mood', models.FloatField(default=1)),
            ],
            options={
                'db_table': 'weights',
                'managed': False,
            },
        ),
    ]
