# Generated by Django 2.2.6 on 2019-11-07 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191107_0102'),
        ('mood_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights_int_list', models.TextField(default='', validators=[django.core.validators.int_list_validator])),
                ('bias_int_list', models.TextField(default='', validators=[django.core.validators.int_list_validator])),
                ('user', models.OneToOneField(null=True, on_delete='models.CASCADE', related_name='weights', to='users.User')),
            ],
        ),
        migrations.DeleteModel(
            name='GoalWeights',
        ),
        migrations.DeleteModel(
            name='ObservationWeights',
        ),
    ]
