# Generated by Django 2.2.6 on 2019-11-07 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191106_0024'),
        ('users', '0002_auto_20191105_1816'),
        ('users', '0002_auto_20191105_1822'),
    ]

    operations = [
    ]
