# Generated by Django 2.2.6 on 2019-11-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20191107_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mood', models.FloatField(default=-1)),
                ('date', models.DateTimeField(verbose_name='date observed')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date observed')),
                ('sleep', models.FloatField(default=-1)),
                ('exercise_24hr', models.FloatField(default=-1)),
                ('meals_24hr', models.IntegerField(default=-1)),
                ('work_24hr', models.FloatField(default=-1)),
            ],
        ),
        migrations.AlterField(
            model_name='goal',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
