# Generated by Django 2.2.6 on 2019-11-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191107_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='exercise_24hr',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='meals_24hr',
            new_name='meals',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='work_24hr',
            new_name='work',
        ),
        migrations.AlterField(
            model_name='goal',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
